openapi: "3.0.0"
info:
  title: IdentityAPI
  version: 1.0.0
paths:
  /getIdentityFromNIC/:
    get:
      summary: Get the identity of the user with nic
      description: Get the identity records from the identityAPI database of the user
      parameters:
        - in: query
          name: nic
          description: nic of the user in the record
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nic:
                    type: integer
                  name:
                    type: string
                  dob:
                    type: date
                  phoneNumber:
                    type: string
                  isMarried:
                    type: boolean
                  isEmployed:
                    type: boolean

        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

      deprecated: false
      security: []

  /getGSDivisionFromNIC/:
    get:
      summary: Get the GS Division of the user with nic
      description: Get the GS Division records from the identityAPI database of the user
      parameters:
        - in: query
          name: nic
          description: nic of the user in the record
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  gsDivision:
                    type: string

        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

      deprecated: false
      security: []
